#pragma once

#ifndef ENTITY_TYPE_H
#define ENTITY_TYPE_H

enum {
	ENTITY_TERRAIN = 0x00,
	ENTITY_PLAYER = 0x01,
	ENTITY_BARREL = 0x02,
	ENTITY_BAT = 0x03,
	ENTITY_PICKAXE = 0x04,
	ENTITY_GHOST = 0x05,
	ENTITY_DROPPABLE = 0x06,
	ENTITY_GENERATOR = 0x07,
	ENTITY_FLASHLIGHT = 0x08,
	ENTITY_BOSS = 0x09
};

#endif